import { EventEmitter, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { RxRecordDefinitionCacheService } from '@helix/platform/record/api';
import { IRuntimeViewConfiguration } from '../interfaces/runtime-view-configuration.interface';
import { IRuntimeViewOutputParameter } from '../interfaces/runtime-view-output-parameter.interface';
import { RuntimeViewLayoutService } from '../layout/runtime-view-layout.service';
import { RuntimeViewModelApi } from '../runtime-view-model-api.class';
import { RuntimeViewModel } from '../runtime-view.model';
import { RxRuntimeViewRegistryService } from '../runtime-view-registry.service';
import { RxViewDefinitionCacheService, RxViewDefinitionService } from '@helix/platform/view/api';
import { RxAssociationDefinitionCacheService } from '@helix/platform/association/api';
import { RxProcessDefinitionCacheService } from '@helix/platform/process/api';
import * as i0 from "@angular/core";
export declare class RuntimeViewComponent implements OnInit, OnChanges, OnDestroy {
    private runtimeViewModelApi;
    private rxRecordDefinitionCacheService;
    runtimeViewLayoutService: RuntimeViewLayoutService;
    runtimeViewModel: RuntimeViewModel;
    private rxProcessDefinitionCacheService;
    private rxRuntimeViewRegistryService;
    private rxViewDefinitionCacheService;
    private rxAssociationDefinitionCacheService;
    private rxViewDefinitionService;
    private destroyed$;
    configuration: IRuntimeViewConfiguration;
    save: EventEmitter<void>;
    closeView: EventEmitter<IRuntimeViewOutputParameter>;
    cancelView: EventEmitter<void>;
    beforeLoad: EventEmitter<void>;
    afterLoad: EventEmitter<void>;
    hostClass: string;
    viewDefinitionGuid: string;
    onTrigger(): void;
    constructor(runtimeViewModelApi: RuntimeViewModelApi, rxRecordDefinitionCacheService: RxRecordDefinitionCacheService, runtimeViewLayoutService: RuntimeViewLayoutService, runtimeViewModel: RuntimeViewModel, rxProcessDefinitionCacheService: RxProcessDefinitionCacheService, rxRuntimeViewRegistryService: RxRuntimeViewRegistryService, rxViewDefinitionCacheService: RxViewDefinitionCacheService, rxAssociationDefinitionCacheService: RxAssociationDefinitionCacheService, rxViewDefinitionService: RxViewDefinitionService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    private init;
    static ɵfac: i0.ɵɵFactoryDeclaration<RuntimeViewComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RuntimeViewComponent, "rx-runtime-view", never, { "configuration": "configuration"; }, { "save": "save"; "closeView": "closeView"; "cancelView": "cancelView"; "beforeLoad": "beforeLoad"; "afterLoad": "afterLoad"; }, never, never>;
}
