import { ChangeDetectorRef, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AdaptTreeNodeTyped, TreeTexts, TreeWrap } from '@bmc-ux/adapt-angular';
import { IAdminNavigationMenuItem, IComponentCanDeactivate, RxAdminSettingsService, RxBundleCacheService, RxComponentCanDeactivateGuard, RxGlobalCacheService, RxPageTitleService } from '@helix/platform/shared/api';
import { RxUtilityModalsService } from '@helix/platform/ui-kit';
import { IRuntimeViewConfiguration, RxRuntimeViewRegistryService } from '@helix/platform/view/runtime';
import { TranslateService } from '@ngx-translate/core';
import { BehaviorSubject, Subscription } from 'rxjs';
import { AdminCommonSettingsComponent } from '../admin-common-settings/admin-common-settings.component';
import { RxAdminSettingsExplorerService } from '../services/admin-settings-explorer.service';
import { AdminSettingViewType } from './admin-settings-explorer.types';
import { RxGainsightConfiguratorService } from '@helix/platform/shared/components';
import * as i0 from "@angular/core";
export declare class AdminSettingsExplorerComponent implements OnInit, OnDestroy, IComponentCanDeactivate {
    private rxAdminSettingsExplorerService;
    private rxAdminSettingsService;
    private rxGlobalCacheService;
    private router;
    private rxBundleCacheService;
    private activatedRoute;
    private rxPageTitleService;
    private rxRuntimeViewRegistryService;
    private rxUtilityModalsService;
    private rxComponentCanDeactivateGuard;
    private changeDetector;
    translateService: TranslateService;
    private rxGainsightConfiguratorService;
    adminCommonSettingsComponent: AdminCommonSettingsComponent;
    navigationTree: AdaptTreeNodeTyped<IAdminNavigationMenuItem>[];
    selectedTreeNodeValue: AdaptTreeNodeTyped<IAdminNavigationMenuItem>;
    runtimeViewConfig: IRuntimeViewConfiguration;
    adminSettingViewType: typeof AdminSettingViewType;
    viewType: AdminSettingViewType;
    componentName$: BehaviorSubject<string>;
    treeWrap: TreeWrap;
    busySubscription: Subscription;
    emptyStateLabel: any;
    texts: TreeTexts;
    private destroyed$;
    private currentSettingGuid;
    get selectedTreeNode(): AdaptTreeNodeTyped<IAdminNavigationMenuItem>;
    set selectedTreeNode(node: AdaptTreeNodeTyped<IAdminNavigationMenuItem>);
    constructor(rxAdminSettingsExplorerService: RxAdminSettingsExplorerService, rxAdminSettingsService: RxAdminSettingsService, rxGlobalCacheService: RxGlobalCacheService, router: Router, rxBundleCacheService: RxBundleCacheService, activatedRoute: ActivatedRoute, rxPageTitleService: RxPageTitleService, rxRuntimeViewRegistryService: RxRuntimeViewRegistryService, rxUtilityModalsService: RxUtilityModalsService, rxComponentCanDeactivateGuard: RxComponentCanDeactivateGuard, changeDetector: ChangeDetectorRef, translateService: TranslateService, rxGainsightConfiguratorService: RxGainsightConfiguratorService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    canDeactivate(): boolean;
    confirmDeactivation(): Promise<boolean>;
    onBeforeLoad(): void;
    onAfterLoad(): void;
    private setPageTitle;
    private findSelectedNode;
    private expandParentNodes;
    private displayView;
    static ɵfac: i0.ɵɵFactoryDeclaration<AdminSettingsExplorerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AdminSettingsExplorerComponent, "rx-admin-settings-explorer", never, {}, {}, never, never>;
}
