import { ComponentFactoryResolver, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { IRecordGridConfig, RecordGridComponent } from '@helix/platform/view/components';
import { ColumnConfig, RowDataItem } from '@bmc-ux/adapt-table';
import { RxModalService } from '@helix/platform/ui-kit';
import { RxDataPageFactoryService, RxNotificationService } from '@helix/platform/shared/api';
import { RxDataSourceConnectionsService } from './data-source-connections.service';
import { AdaptModalService } from '@bmc-ux/adapt-angular';
import { IDataSourceConnectionWizardContext } from './data-source-connections.types';
import { RxWizardService } from '@helix/platform/shared/components';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare class DataSourceConnectionsAdminComponent implements OnInit {
    private rxModalService;
    private rxDataPageService;
    private rxDataSourceConnectionsService;
    private rxNotificationService;
    private adaptModalService;
    private componentFactoryResolver;
    private rxWizardService;
    private translateService;
    dataSourceConnectionsGrid: RecordGridComponent;
    private resource;
    private selectedConnectionId;
    private wizardTitle;
    private finishButtonLabel;
    recordGridConfig: Observable<IRecordGridConfig>;
    wizardConfigData: IDataSourceConnectionWizardContext;
    constructor(rxModalService: RxModalService, rxDataPageService: RxDataPageFactoryService, rxDataSourceConnectionsService: RxDataSourceConnectionsService, rxNotificationService: RxNotificationService, adaptModalService: AdaptModalService, componentFactoryResolver: ComponentFactoryResolver, rxWizardService: RxWizardService, translateService: TranslateService);
    ngOnInit(): void;
    private getData;
    getCellValue(dataItem: string[], column: ColumnConfig): string;
    createDataSourceConnection(): void;
    editDataSourceConnection(dataItem: RowDataItem): void;
    private refreshDataSourceConnectionsGrid;
    openWizard(): void;
    save(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DataSourceConnectionsAdminComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DataSourceConnectionsAdminComponent, "rx-admin-data-source-connections", never, {}, {}, never, never>;
}
