import { Injector, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { DockedPanelContext, RxSelectOption } from '@bmc-ux/adapt-angular';
import { RxRecordDefinitionCacheService, RxRecordInstanceService } from '@helix/platform/record/api';
import { RxModalClass } from '@helix/platform/ui-kit';
import { RxJsonParserService } from '@helix/platform/utils';
import { TranslateService } from '@ngx-translate/core';
import { RxGlobalCacheService, RxNotificationService, RxOverlayService } from '@helix/platform/shared/api';
import { IMetadataField } from '../webhook-callback-configuration.interface';
import { RxWebhookCallbackConfigurationService } from '../webhook-callback-configuration.service';
import * as i0 from "@angular/core";
export declare class WebhookCallbackConfigurationEditorComponent extends RxModalClass implements OnInit {
    private dockedPanelContext;
    private rxGlobalCacheService;
    private rxRecordDefinitionCacheService;
    private rxRecordInstanceService;
    private rxWebhookCallbackConfigurationService;
    private rxOverlayService;
    private rxJsonParserService;
    private rxNotificationService;
    private formBuilder;
    private translateService;
    protected injector: Injector;
    private defaultControls;
    private recordInstance;
    metadataFields: IMetadataField[];
    bundleIdOptions: RxSelectOption[];
    processorOptions: RxSelectOption[];
    isEditMode: boolean;
    callbackUrl: string;
    webhookCallbackConfigurationForm: FormGroup;
    constructor(dockedPanelContext: DockedPanelContext, rxGlobalCacheService: RxGlobalCacheService, rxRecordDefinitionCacheService: RxRecordDefinitionCacheService, rxRecordInstanceService: RxRecordInstanceService, rxWebhookCallbackConfigurationService: RxWebhookCallbackConfigurationService, rxOverlayService: RxOverlayService, rxJsonParserService: RxJsonParserService, rxNotificationService: RxNotificationService, formBuilder: FormBuilder, translateService: TranslateService, injector: Injector);
    ngOnInit(): void;
    isDirty(): boolean;
    private setFormControlValues;
    private removeMetadataFieldFormControls;
    private generateMetadataFieldFormControls;
    loadMetadataFields(): void;
    saveConfiguration(): void;
    private successCallback;
    optionFormatter(option: RxSelectOption): string;
    cancel(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<WebhookCallbackConfigurationEditorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WebhookCallbackConfigurationEditorComponent, "rx-webhook-callback-configuration", never, {}, {}, never, never>;
}
