import { OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { RxChatbotDefinitionService } from '@helix/platform/chatbot/api';
import { IRecordDefinition } from '@helix/platform/record/api';
import { IBundleDescriptor, IDataPageResult, RxBundleCacheService, RxChatbotDefinitionDataPageService, RxDefinitionNameService, RxOverlayService } from '@helix/platform/shared/api';
import { RxModalService } from '@helix/platform/ui-kit';
import { IRowDataItem } from '@helix/platform/view/api';
import { IRecordGridColumn } from '@helix/platform/view/components';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { IRenameAction } from '../bundle-definitions/bundle-definitions.types';
import { IDefinitionActionConfig } from '../bundle-details/bundle-details.types';
import { DefinitionTabComponent } from '../definition-tab/definition-tab.component';
import * as i0 from "@angular/core";
export declare class ChatbotDefinitionTabComponent implements OnInit {
    private router;
    private rxChatbotDefinitionDataPageService;
    private rxDefinitionNameService;
    private rxOverlayService;
    private rxBundleCacheService;
    private rxModalService;
    private translateService;
    private rxChatbotDefinitionService;
    bundleDescriptor: IBundleDescriptor;
    definitionTabComponent: DefinitionTabComponent;
    private rowSelectionChanged$;
    definitionActions$: Observable<IDefinitionActionConfig[]>;
    definitions$: Observable<IDataPageResult>;
    gridColumns: IRecordGridColumn[];
    isActionInProgress: boolean;
    recordDefinition: Partial<IRecordDefinition>;
    botNameMaxLength: number;
    constructor(router: Router, rxChatbotDefinitionDataPageService: RxChatbotDefinitionDataPageService, rxDefinitionNameService: RxDefinitionNameService, rxOverlayService: RxOverlayService, rxBundleCacheService: RxBundleCacheService, rxModalService: RxModalService, translateService: TranslateService, rxChatbotDefinitionService: RxChatbotDefinitionService);
    private getDefinitionActions;
    ngOnInit(): void;
    onAddDefinition(): void;
    onRenameDefinition({ selectedRow, definitionNames }: IRenameAction): void;
    onDeleteDefinition(selectedRows: IRowDataItem[]): void;
    onRowSelectionChanged(selectedRows: IRowDataItem[]): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ChatbotDefinitionTabComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ChatbotDefinitionTabComponent, "ax-chatbot-definition-tab", never, { "bundleDescriptor": "bundleDescriptor"; }, {}, never, never>;
}
