import { OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { AdaptTreeNode, RxSelectOption, TreeWrap } from '@bmc-ux/adapt-angular';
import { RxDocumentDefinitionService } from '@helix/platform/document/api';
import { RxDefinitionNameService } from '@helix/platform/shared/api';
import { RxWizardModalComponent } from '@helix/platform/shared/components';
import { RxJsonParserService } from '@helix/platform/utils';
import { IRecordGridConfig, RecordGridComponent } from '@helix/platform/view/components';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { IWebApiDocumentSchemaField, IWebApiDocumentTreeNode } from '../external-record-wizard.types';
import * as i0 from "@angular/core";
export declare class FieldTreeSelectionStepComponent implements OnInit, OnDestroy {
    private rxDefinitionNameService;
    private rxDocumentDefinitionService;
    private rxJsonParserService;
    private rxWizardModalComponent;
    private translateService;
    recordGrid: RecordGridComponent;
    typeCellTemplate: TemplateRef<any>;
    deleteCellTemplate: TemplateRef<any>;
    availableFieldsSectionLabel: string;
    mapToDisplayIdLabel: string;
    mapToIdLabel: string;
    selectedFieldsSectionLabel: string;
    documentName: string;
    documentTree: AdaptTreeNode[];
    recordGridConfig$: Observable<IRecordGridConfig>;
    selectedDocumentTreeNodes: IWebApiDocumentTreeNode[];
    treeWrap: TreeWrap;
    selectedDocumentSchemaFields: IWebApiDocumentSchemaField[];
    selectedFieldsGroup: FormGroup;
    mappingGroup: FormGroup;
    supportedFieldTypes: string[];
    fieldTypes: RxSelectOption[];
    private destroyed$;
    constructor(rxDefinitionNameService: RxDefinitionNameService, rxDocumentDefinitionService: RxDocumentDefinitionService, rxJsonParserService: RxJsonParserService, rxWizardModalComponent: RxWizardModalComponent, translateService: TranslateService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    getCoreFieldMappingOptions(): IWebApiDocumentSchemaField[];
    optionFormatter(selectOption: RxSelectOption): string;
    selectFields(): void;
    unselectField(field: IWebApiDocumentSchemaField): void;
    private prepareTreeForAdapt;
    private deepProcessJson;
    private flattenListStructure;
    static ɵfac: i0.ɵɵFactoryDeclaration<FieldTreeSelectionStepComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FieldTreeSelectionStepComponent, "ax-field-tree-selection-step", never, {}, {}, never, never>;
}
