import { OnDestroy, OnInit } from '@angular/core';
import { RxAssociationDefinitionDataPageService } from '@helix/platform/association/api';
import { RxDocumentDefinitionDataPageService } from '@helix/platform/document/api';
import { RxeventStatisticsDefinitionDataPageService } from '@helix/platform/event-statistics/api';
import { RxEventDefinitionDataPageService } from '@helix/platform/event/api';
import { RxNamedListDefinitionDataPageService } from '@helix/platform/named-list/api';
import { RxProcessDefinitionDataPageService } from '@helix/platform/process/api';
import { RxRecordDefinitionDataPageService } from '@helix/platform/record/api';
import { RxRuleDefinitionDataPageService } from '@helix/platform/rule/api';
import { IPlainObject, RxDefinitionNameService, RxSessionExpirationService } from '@helix/platform/shared/api';
import { RxWizardModalComponent } from '@helix/platform/shared/components';
import { RxStringService } from '@helix/platform/utils';
import { RxViewDefinitionDataPageService } from '@helix/platform/view/api';
import { IRecordGridConfig } from '@helix/platform/view/components';
import { RxWebApiDefinitionDataPageService } from '@helix/platform/web-api/api';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import * as i0 from "@angular/core";
export declare class SelectDefinitionsWizardStepComponent implements OnInit, OnDestroy {
    private rxWizardModalComponent;
    private rxAssociationDefinitionDataPageService;
    private rxDefinitionNameService;
    private rxDocumentDefinitionDataPageService;
    private rxEventDefinitionDataPageService;
    private rxEventStatisticsDefinitionDataPageService;
    private rxNamedListDefinitionDataPageService;
    private rxProcessDefinitionDataPageService;
    private rxRecordDefinitionDataPageService;
    private rxRuleDefinitionDataPageService;
    private rxSessionExpirationService;
    private rxStringService;
    private rxViewDefinitionDataPageService;
    private rxWebApiDefinitionDataPageService;
    private translateService;
    options: IPlainObject;
    private recordGrid;
    selectedDefinitionCount: number;
    recordGridConfig$: Observable<IRecordGridConfig>;
    private destroyed$;
    constructor(rxWizardModalComponent: RxWizardModalComponent, rxAssociationDefinitionDataPageService: RxAssociationDefinitionDataPageService, rxDefinitionNameService: RxDefinitionNameService, rxDocumentDefinitionDataPageService: RxDocumentDefinitionDataPageService, rxEventDefinitionDataPageService: RxEventDefinitionDataPageService, rxEventStatisticsDefinitionDataPageService: RxeventStatisticsDefinitionDataPageService, rxNamedListDefinitionDataPageService: RxNamedListDefinitionDataPageService, rxProcessDefinitionDataPageService: RxProcessDefinitionDataPageService, rxRecordDefinitionDataPageService: RxRecordDefinitionDataPageService, rxRuleDefinitionDataPageService: RxRuleDefinitionDataPageService, rxSessionExpirationService: RxSessionExpirationService, rxStringService: RxStringService, rxViewDefinitionDataPageService: RxViewDefinitionDataPageService, rxWebApiDefinitionDataPageService: RxWebApiDefinitionDataPageService, translateService: TranslateService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    onDataLoaded(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SelectDefinitionsWizardStepComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SelectDefinitionsWizardStepComponent, "ax-select-definitions-wizard-step", never, { "options": "options"; }, {}, never, never>;
}
