import { Injector, OnDestroy, OnInit } from '@angular/core';
import { AbstractControl, NgForm, ValidationErrors } from '@angular/forms';
import { DockedPanelContext, RxSelectOption } from '@bmc-ux/adapt-angular';
import { IRole, RxGlobalCacheService, RxGroupDataPageService, RxNotificationService } from '@helix/platform/shared/api';
import { RxModalClass } from '@helix/platform/ui-kit';
import { TranslateService } from '@ngx-translate/core';
import { OperatorFunction, Subscription } from 'rxjs';
import { RxRolePermissionsService } from '../role-permissions.service';
import * as i0 from "@angular/core";
export declare class RoleEditorComponent extends RxModalClass implements OnInit, OnDestroy {
    private rxGlobalCacheService;
    private rxGroupDataPageService;
    private rxRolePermissionsService;
    private rxNotificationService;
    private dockedPanelContext;
    private translateService;
    protected injector: Injector;
    role: IRole;
    roleEditorForm: NgForm;
    applicationOptions: RxSelectOption[];
    busy: Subscription;
    groupList: string[];
    isEditMode: boolean;
    isSaveInProgress: boolean;
    isSaveButtonDisabled: boolean;
    selectedApplication: RxSelectOption;
    maxRoleId: number;
    minRoleId: number;
    oldRoleName: string;
    validDefinitionNameRegex: RegExp;
    private destroyed$;
    validatorFn: any;
    constructor(rxGlobalCacheService: RxGlobalCacheService, rxGroupDataPageService: RxGroupDataPageService, rxRolePermissionsService: RxRolePermissionsService, rxNotificationService: RxNotificationService, dockedPanelContext: DockedPanelContext, translateService: TranslateService, injector: Injector);
    testSearch: OperatorFunction<string, string[]>;
    productionSearch: OperatorFunction<string, string[]>;
    ngOnInit(): void;
    isDirty(): boolean;
    optionFormatter(option: RxSelectOption): string;
    save(): void;
    getGroupList(): void;
    getApplicationList(): void;
    closeModal(): void;
    roleNameValidator(control: AbstractControl): ValidationErrors | null;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<RoleEditorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RoleEditorComponent, "rx-role-editor", never, {}, {}, never, never>;
}
