import { OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { RxEventDefinitionDataPageService, RxEventDefinitionService } from '@helix/platform/event/api';
import { IRecordDefinition } from '@helix/platform/record/api';
import { IBundleDescriptor, IDataPageResult, RxBundleCacheService, RxCommandFactoryService, RxOverlayService } from '@helix/platform/shared/api';
import { RxModalService } from '@helix/platform/ui-kit';
import { IRowDataItem } from '@helix/platform/view/api';
import { IRecordGridColumn } from '@helix/platform/view/components';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { IDefinitionActionConfig } from '../bundle-details/bundle-details.types';
import { DefinitionTabComponent } from '../definition-tab/definition-tab.component';
import { RxCopyDefinitionService } from '../copy-definition/copy-definition.service';
import * as i0 from "@angular/core";
export declare class EventDefinitionTabComponent implements OnInit {
    private rxEventDefinitionDataPageService;
    private rxOverlayService;
    private translateService;
    private rxModalService;
    private rxCommandFactoryService;
    private rxBundleCacheService;
    private rxEventDefinitionService;
    private rxCopyDefinitionService;
    private router;
    bundleDescriptor: IBundleDescriptor;
    definitionTabComponent: DefinitionTabComponent;
    private rowSelectionChanged$;
    gridColumns: IRecordGridColumn[];
    definitions$: Observable<IDataPageResult>;
    recordDefinition: Partial<IRecordDefinition>;
    isActionInProgress: boolean;
    definitionActions$: Observable<IDefinitionActionConfig[]>;
    constructor(rxEventDefinitionDataPageService: RxEventDefinitionDataPageService, rxOverlayService: RxOverlayService, translateService: TranslateService, rxModalService: RxModalService, rxCommandFactoryService: RxCommandFactoryService, rxBundleCacheService: RxBundleCacheService, rxEventDefinitionService: RxEventDefinitionService, rxCopyDefinitionService: RxCopyDefinitionService, router: Router);
    ngOnInit(): void;
    private getDefinitionActions;
    onAddDefinition(): void;
    onRowSelectionChanged(selectedRows: IRowDataItem[]): void;
    onDeleteDefinition(selectedRows: IRowDataItem[]): void;
    onRevertCustomization(selectedRows: IRowDataItem[]): void;
    onCopyDefinition(row: IRowDataItem): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EventDefinitionTabComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EventDefinitionTabComponent, "ax-event-definition-tab", never, { "bundleDescriptor": "bundleDescriptor"; }, {}, never, never>;
}
