import { OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { IRecordDefinition } from '@helix/platform/record/api';
import { IBundleDescriptor, IDataPageResult, RxBundleCacheService, RxCommandFactoryService, RxOverlayService } from '@helix/platform/shared/api';
import { RxModalService } from '@helix/platform/ui-kit';
import { IRowDataItem, RxViewDefinitionDataPageService, RxViewDefinitionService } from '@helix/platform/view/api';
import { IRecordGridColumn } from '@helix/platform/view/components';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { ICustomAction, IRenameAction } from '../bundle-definitions/bundle-definitions.types';
import { IDefinitionActionConfig } from '../bundle-details/bundle-details.types';
import { RxCopyDefinitionService } from '../copy-definition/copy-definition.service';
import { DefinitionTabComponent } from '../definition-tab/definition-tab.component';
import * as i0 from "@angular/core";
export declare class ViewDefinitionTabComponent implements OnInit {
    private rxOverlayService;
    private rxViewDefinitionDataPageService;
    private rxModalService;
    private translateService;
    private rxCommandFactoryService;
    private router;
    private rxBundleCacheService;
    private rxViewDefinitionService;
    private rxCopyDefinitionService;
    bundleDescriptor: IBundleDescriptor;
    definitionTabComponent: DefinitionTabComponent;
    private rowSelectionChanged$;
    private areNewDefinitionsAllowed;
    definitionActions$: Observable<IDefinitionActionConfig[]>;
    definitions$: Observable<IDataPageResult>;
    gridColumns: IRecordGridColumn[];
    isActionInProgress: boolean;
    recordDefinition: Partial<IRecordDefinition>;
    constructor(rxOverlayService: RxOverlayService, rxViewDefinitionDataPageService: RxViewDefinitionDataPageService, rxModalService: RxModalService, translateService: TranslateService, rxCommandFactoryService: RxCommandFactoryService, router: Router, rxBundleCacheService: RxBundleCacheService, rxViewDefinitionService: RxViewDefinitionService, rxCopyDefinitionService: RxCopyDefinitionService);
    private getNewViewSubAction;
    private getDefinitionActions;
    ngOnInit(): void;
    onCustomAction(event: ICustomAction): void;
    onCopyDefinition(row: IRowDataItem): void;
    onDeleteDefinition(selectedRows: IRowDataItem[]): void;
    onRenameDefinition({ selectedRow, definitionNames }: IRenameAction): void;
    onRevertCustomization(selectedRows: IRowDataItem[]): void;
    onRowSelectionChanged(selectedRows: IRowDataItem[]): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ViewDefinitionTabComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ViewDefinitionTabComponent, "ax-view-definition-tab", never, { "bundleDescriptor": "bundleDescriptor"; }, {}, never, never>;
}
