import { OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { IRecordGridConfig, RecordGridComponent } from '@helix/platform/view/components';
import { IRecordDefinition, RxRecordDefinitionCacheService } from '@helix/platform/record/api';
import { RxBundleCacheService, RxDefinitionNameService, RxGlobalCacheService, RxPageTitleService } from '@helix/platform/shared/api';
import { ActivatedRoute, Router } from '@angular/router';
import { RxRecordEditorBuilder } from './record-editor-builder.service';
import { ViewComponentEventManager } from '@helix/platform/view/runtime';
import { RxEditRecordsViewActionService, RxOpenViewActionService } from '@helix/platform/view/actions';
import * as i0 from "@angular/core";
export declare class RecordDataEditorComponent implements OnInit, OnDestroy {
    private rxRecordEditorBuilder;
    private route;
    private router;
    private translateService;
    private rxDefinitionNameService;
    private rxGlobalCacheService;
    private rxPageTitleService;
    private rxRecordDefinitionCacheService;
    private rxBundleCacheService;
    private viewComponentEventManager;
    private rxOpenViewActionService;
    private rxEditRecordsViewActionService;
    private destroyed$;
    recordDefinition: IRecordDefinition;
    isCustomRecordDefinition: boolean;
    constructor(rxRecordEditorBuilder: RxRecordEditorBuilder, route: ActivatedRoute, router: Router, translateService: TranslateService, rxDefinitionNameService: RxDefinitionNameService, rxGlobalCacheService: RxGlobalCacheService, rxPageTitleService: RxPageTitleService, rxRecordDefinitionCacheService: RxRecordDefinitionCacheService, rxBundleCacheService: RxBundleCacheService, viewComponentEventManager: ViewComponentEventManager, rxOpenViewActionService: RxOpenViewActionService, rxEditRecordsViewActionService: RxEditRecordsViewActionService);
    dataEditorGrid: RecordGridComponent;
    displayIdColumnTemplate: TemplateRef<any>;
    recordDefinitionName$: Observable<any>;
    recordDefinition$: Observable<IRecordDefinition>;
    dataEditorGridConfig$: Observable<IRecordGridConfig>;
    ngOnInit(): void;
    close(): void;
    createRecord(): void;
    ngOnDestroy(): void;
    editRecord(recordInstanceId: string): void;
    private isRecordEditable;
    private setPageTitle;
    static ɵfac: i0.ɵɵFactoryDeclaration<RecordDataEditorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RecordDataEditorComponent, "ax-record-data-editor", never, {}, {}, never, never>;
}
