import { EventEmitter, OnInit, QueryList } from '@angular/core';
import { IPlainObject, RxAdminSettingsService, RxNotificationService } from '@helix/platform/shared/api';
import { FormBuilderComponent } from '@helix/platform/shared/components';
import { RxModalService } from '@helix/platform/ui-kit';
import { IRecordGridConfig, RecordGridComponent } from '@helix/platform/view/components';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { ICommonSettingsGroup } from '../admin-common-settings/admin-common-settings.types';
import { RxAdminFileUtilityService } from '../services/admin-file-utility.service';
import { IGetRecordGridConfigParams, IOpenSettingsDetailsParams } from '../services/admin-common-settings.types';
import { AdaptDockedPanelComponent } from '@bmc-ux/adapt-angular';
import * as i0 from "@angular/core";
export declare class AdminCommonSettingsEditorComponent implements OnInit {
    private rxAdminSettingsService;
    private rxAdminFileUtilityService;
    private rxNotificationService;
    private rxModalService;
    private translateService;
    componentName: string;
    ownerKeyValue: string;
    groups: ICommonSettingsGroup[];
    createPermission: boolean;
    isNew: boolean;
    isChildSetting: boolean;
    childOwnerKeyValue: string;
    getRecordGridConfig: (options: IGetRecordGridConfigParams) => Observable<IRecordGridConfig>;
    openSettingsDetails: (options: IOpenSettingsDetailsParams) => Promise<any>;
    closeEditor: EventEmitter<void>;
    busy: EventEmitter<boolean>;
    save: EventEmitter<void>;
    recordGridInstances: QueryList<RecordGridComponent>;
    forms: QueryList<FormBuilderComponent>;
    class: string;
    private generalSettings;
    private assigneeGroup;
    isSettingsActionsAvailable: boolean;
    isInDockedPanel: boolean;
    private dialogApi;
    constructor(rxAdminSettingsService: RxAdminSettingsService, rxAdminFileUtilityService: RxAdminFileUtilityService, rxNotificationService: RxNotificationService, rxModalService: RxModalService, translateService: TranslateService, adaptDockedPanelComponent: AdaptDockedPanelComponent);
    ngOnInit(): void;
    addNewSetting(group: ICommonSettingsGroup): Promise<any>;
    private getCurrentGrid;
    private setChildSettings;
    onModelChange(model: IPlainObject, group: ICommonSettingsGroup): void;
    private setGroupSettingValues;
    private getSettingWithValue;
    saveSettings(): void;
    isAbleToSave(): boolean;
    resetSettings(): void;
    onCancel(): void;
    canClose(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<AdminCommonSettingsEditorComponent, [null, null, null, null, null, { optional: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AdminCommonSettingsEditorComponent, "rx-admin-common-settings-editor", never, { "componentName": "componentName"; "ownerKeyValue": "ownerKeyValue"; "groups": "groups"; "createPermission": "createPermission"; "isNew": "isNew"; "isChildSetting": "isChildSetting"; "childOwnerKeyValue": "childOwnerKeyValue"; "getRecordGridConfig": "getRecordGridConfig"; "openSettingsDetails": "openSettingsDetails"; }, { "closeEditor": "closeEditor"; "busy": "busy"; "save": "save"; }, never, never>;
}
