import { EventEmitter, OnInit } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { IFormBuilderEvent, IPlainObject, RxBundleCacheService, RxDefinitionNameService, RxGlobalCacheService, RxOverlayService } from '@helix/platform/shared/api';
import { IBreadcrumbItem, IValidationIssue, IValidationIssueSection } from '@helix/platform/ui-kit';
import { INamedListDefinition } from '@helix/platform/named-list/api';
import * as i0 from "@angular/core";
export declare class RxEventDesignerComponent implements OnInit {
    private rxGlobalCacheService;
    private rxBundleCacheService;
    private rxDefinitionNameService;
    private translateService;
    private rxOverlayService;
    eventDefinitionName: string;
    eventDefinitionSaved: EventEmitter<string>;
    eventDefinitionErrorLoading: EventEmitter<void>;
    closeDesigner: EventEmitter<void>;
    isDesignMode: boolean;
    isExistingEvent: boolean;
    isCustomizationEnabled: boolean;
    bundleFriendlyName$: Observable<string>;
    validationIssues$: BehaviorSubject<IValidationIssueSection[]>;
    hasValidationErrors$: Observable<boolean>;
    breadcrumbItems$: Observable<IBreadcrumbItem[]>;
    eventDefinition$: BehaviorSubject<INamedListDefinition>;
    isSaveButtonDisabled$: Observable<boolean>;
    isSavingInProgress$: BehaviorSubject<boolean>;
    private bundleId;
    private isBundleEditable;
    private destroyed$;
    constructor(rxGlobalCacheService: RxGlobalCacheService, rxBundleCacheService: RxBundleCacheService, rxDefinitionNameService: RxDefinitionNameService, translateService: TranslateService, rxOverlayService: RxOverlayService);
    ngOnInit(): void;
    canDeactivate(): boolean;
    toggleDesignMode(): void;
    onCorrectIssue(validationIssue: IValidationIssue): void;
    validate(value: IPlainObject): IValidationIssueSection[];
    onRevertCustomization(event: IFormBuilderEvent): void;
    saveDefinition(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<RxEventDesignerComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<RxEventDesignerComponent, "rx-event-designer", never, { "eventDefinitionName": "eventDefinitionName"; }, { "eventDefinitionSaved": "eventDefinitionSaved"; "eventDefinitionErrorLoading": "eventDefinitionErrorLoading"; "closeDesigner": "closeDesigner"; }, never, never>;
}
